"""
This type stub file was generated by pyright.
"""

log = ...
def create(addr=..., port=..., options=...): # -> MitmProxy:
    """Create a new proxy backend.

    Args:
        addr: The address the proxy server will listen on. Default 127.0.0.1.
        port: The port the proxy server will listen on. Default 0 - which means
            use the first available port.
        options: Additional options to configure the proxy.

    Returns:
        An instance of the proxy backend.
    """
    ...

