"""
This type stub file was generated by pyright.
"""

log = ...
class InterceptRequestHandler:
    """Mitmproxy add-on which is responsible for request modification
    and capture.
    """
    def __init__(self, proxy) -> None:
        ...
    
    def requestheaders(self, flow): # -> None:
        ...
    
    def request(self, flow): # -> None:
        ...
    
    def in_scope(self, request): # -> bool:
        ...
    
    def responseheaders(self, flow): # -> None:
        ...
    
    def response(self, flow): # -> None:
        ...
    
    def websocket_message(self, flow): # -> None:
        ...
    


