"""
This type stub file was generated by pyright.
"""

logger = ...
DEFAULT_VERIFY_SSL = ...
DEFAULT_STREAM_WEBSOCKETS = ...
DEFAULT_SUPPRESS_CONNECTION_ERRORS = ...
class MitmProxy:
    """Run and manage a mitmproxy server instance."""
    def __init__(self, host, port, options) -> None:
        ...
    
    def serve_forever(self): # -> None:
        """Run the server."""
        ...
    
    def address(self):
        """Get a tuple of the address and port the proxy server
        is listening on.
        """
        ...
    
    def shutdown(self): # -> None:
        """Shutdown the server and perform any cleanup."""
        ...
    


class SendToLogger:
    def log(self, entry): # -> None:
        """Send a mitmproxy log message through our own logger."""
        ...
    


